---
  - block:
      - name: Install cmd line tools (wget, unzip)
        ansible.builtin.apt:
          name:
            - wget
            - unzip
          state: present
      - name: Download Loki binary
        ansible.builtin.get_url:
          url: https://github.com/grafana/loki/releases/download/v2.4.1/loki-linux-amd64.zip
          dest: /tmp/loki-linux-amd64.zip
          mode: '0644'
      - name: Unzip Loki binary
        ansible.builtin.unarchive:
          src: /tmp/loki-linux-amd64.zip
          dest: /usr/local/bin/
          remote_src: true
          creates: /usr/local/bin/loki
      - name: Rename Loki binary to "loki"
        ansible.builtin.command:
          cmd: mv /usr/local/bin/loki-linux-amd64 /usr/local/bin/loki
        args:
          removes: /usr/local/bin/loki-linux-amd64
      - name: Create Loki directory
        ansible.builtin.file:
          path: /etc/loki
          state: directory
          mode: '0755'
      - name: Copy Loki configuration file
        ansible.builtin.copy:
          dest: /etc/loki/loki.yaml
          content: |
            auth_enabled: false

            server:
              http_listen_port: 3100

            ingester:
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1
              chunk_idle_period: 15m

            schema_config:
              configs:
                - from: 2020-02-25
                  store: boltdb
                  object_store: filesystem
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h

            storage_config:
              boltdb:
                directory: /tmp/loki/index

            limits_config:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 168h

            chunk_store_config:
              max_look_back_period: 0s

          owner: root
          mode: '0644'
        tags:
          - CreateLokiConfig
      - name: Create systemd service config for Loki
        ansible.builtin.copy:
          content: |
            [Unit]
            Description=Loki Service
            After=network.target

            [Service]
            ExecStart=/usr/local/bin/loki -config.file=/etc/loki/loki.yaml
            Restart=always
            User=root
            Group=root
            LimitNOFILE=4096

            [Install]
            WantedBy=multi-user.target
          dest: /etc/systemd/system/loki.service
          mode: '0644'
      - name: Reload systemd
        ansible.builtin.systemd:
          daemon_reload: true
      - name: Enable and start Loki service
        ansible.builtin.systemd:
          name: loki
          enabled: true
          state: started
