---
    - block:
        - name: Enable UFW if it's not already enabled
          community.general.ufw:
            state: enabled

        - name: Allow port 443 through the firewall (UFW)
          community.general.ufw:
            rule: allow
            port: "{{ firewall_https_port }}"
            proto: "{{ firewall_https_protocol }}"
          tags:
            - https

        - name: Allow port 80 through the firewall (UFW)
          community.general.ufw:
            rule: allow
            port: "{{ firewall_http_port }}"
            proto: "{{ firewall_http_protocol }}"
          tags:
            - http

        - name: Allow port loki 3100 through the firewall (UFW)
          community.general.ufw:
            rule: allow
            port: "{{ loki_port }}"
            proto: "{{ firewall_http_protocol }}"
          tags:
            - loki

        - name: Allow port grpc 9095 through the firewall (UFW)
          community.general.ufw:
            rule: allow
            port: "{{ grpc_port }}"
            proto: "{{ firewall_http_protocol }}"
          tags:
            - grpc
