---
  - block:
    - name: Creater user devops
      ansible.builtin.user:
        name: devops
        state: present
        shell: /bin/bash
    - name: Add user to the sudo group
      ansible.builtin.user:
        name: devops
        groups: sudo
        append: true
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ devops_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ devops_user }}"
        group: "{{ devops_user }}"
    - name: Copy the local public key to the remote server
      ansible.builtin.copy:
        src: "{{ local_ssh_key }}"
        dest: "/home/{{ devops_user }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ devops_user }}"
        group: "{{ devops_user }}"
    - name: Create nonprivileged user bob
      ansible.builtin.user:
        name: "{{ normal_user }}"
        state: present
        shell: /bin/bash
    - name: Allow bob reboot sudoless privilege
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^{{ normal_user }}'
        line: '{{ normal_user }} ALL=(ALL) NOPASSWD: /sbin/reboot'
        validate: visudo -cf %s
